/* eslint-disable react/no-unescaped-entities */
import { Search, Handshake } from "lucide-react";

const BentoFeatures = () => {
  return (
    <section id="features" className="py-24 relative">
      <div className="absolute inset-0 grid-pattern opacity-30" />

      <div className="container mx-auto px-6 relative z-10">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
            Feature <span className="text-primary text-glow">Deep Dive</span>
          </h2>
          <div className="w-24 h-px bg-gradient-to-r from-transparent via-primary to-transparent mx-auto" />
        </div>

        {/* Bento Grid */}
        <div className="grid lg:grid-cols-2 gap-6">
          {/* Large Module - Left */}
          <div className="glass-card p-8 glow-border row-span-2 flex flex-col">
            <div className="font-mono text-xs text-primary/60 tracking-widest mb-4">
              TRACEABILITY
            </div>
            <h3 className="text-2xl font-semibold text-foreground mb-4">
              Prompt-to-Code Traceability
            </h3>

            {/* Mockup */}
            <div className="flex-1 bg-background/50 rounded-lg p-4 border border-border overflow-hidden">
              <div className="flex items-center gap-2 mb-3">
                <div className="w-3 h-3 rounded-full bg-destructive/60" />
                <div className="w-3 h-3 rounded-full bg-yellow-500/60" />
                <div className="w-3 h-3 rounded-full bg-green-500/60" />
              </div>

              <div className="font-mono text-xs space-y-2">
                <div className="text-muted-foreground">
                  <span className="text-secondary">const</span>{" "}
                  <span className="text-primary">PaymentButton</span> = (){" "}
                  {"=> {"}
                </div>
                <div className="text-muted-foreground pl-4">
                  <span className="text-secondary">return</span> (
                </div>
                <div className="relative pl-8">
                  <span className="text-muted-foreground">{"<button"}</span>
                  <span className="text-primary"> className</span>
                  <span className="text-muted-foreground">
                    ="fixed bottom-0..."{">"}
                  </span>

                  {/* Tooltip */}
                  <div className="absolute -top-16 left-0 right-0 glass p-3 rounded-lg border border-primary/30 shadow-lg">
                    <div className="font-mono text-xs">
                      <span className="text-primary/70">
                        Generated by prompt:
                      </span>
                      <p className="text-foreground mt-1 italic">
                        "Make the payment button stick to bottom on mobile"
                      </p>
                    </div>
                    <div className="absolute bottom-0 left-8 w-0 h-0 border-l-8 border-r-8 border-t-8 border-transparent border-t-primary/30 translate-y-full" />
                  </div>
                </div>
                <div className="text-muted-foreground pl-8">Pay Now</div>
                <div className="text-muted-foreground pl-8">{"</button>"}</div>
                <div className="text-muted-foreground pl-4">)</div>
                <div className="text-muted-foreground">{"}"}</div>
              </div>
            </div>
          </div>

          {/* Medium Module - Top Right */}
          <div className="glass-card p-8 glow-border flex flex-col">
            <div className="font-mono text-xs text-primary/60 tracking-widest mb-4">
              SEARCH
            </div>
            <h3 className="text-xl font-semibold text-foreground mb-4">
              Plain English Search
            </h3>

            {/* Search mockup */}
            <div className="bg-background/50 rounded-lg p-4 border border-border">
              <div className="flex items-center gap-3 mb-4">
                <Search className="w-5 h-5 text-primary" />
                <div className="flex-1 font-mono text-sm text-foreground">
                  Where do I change pricing?
                </div>
              </div>

              <div className="border-t border-border pt-3">
                <div className="flex items-center gap-2 text-sm">
                  <div className="w-2 h-2 rounded-full bg-primary" />
                  <span className="font-mono text-muted-foreground">
                    src/config/
                  </span>
                  <span className="font-mono text-primary">pricing.ts</span>
                  <span className="font-mono text-muted-foreground">:42</span>
                </div>
              </div>
            </div>
          </div>

          {/* Medium Module - Bottom Right */}
          <div className="glass-card p-8 glow-border flex flex-col">
            <div className="font-mono text-xs text-primary/60 tracking-widest mb-4">
              HANDOFF
            </div>
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                <Handshake className="w-6 h-6 text-primary" />
              </div>
              <div>
                <h3 className="text-xl font-semibold text-foreground mb-2">
                  The 'Exit Pack' Generator
                </h3>
                <p className="font-mono text-sm text-muted-foreground">
                  One-click PDF report for handing off to buyers or new hires.
                  Complete with architecture diagrams, dependency maps, and
                  onboarding guides.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default BentoFeatures;
